# Generated by Django 4.1.2 on 2022-10-24 10:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 24, 18, 23, 3, 8795), verbose_name='date created'),
        ),
    ]
